import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    header: {
      searchPlaceholder: 'Search Chai...',
      searchPrompt: 'Search our shop by name, blend, or item.',
      searchNoResults: 'No matches found. Try another flavor.',
      cancel: 'Cancel',
      clearSearch: 'Clear search',
      openSearch: 'Open search',
      changeLanguage: 'Change language',
      shop: 'Shop',
      cart: 'Cart',
      profile: 'Profile',
      login: 'Login',
      logout: 'Logout',
      notifications: 'Notifications',
      notificationsPrompt: 'Tap an item or use actions',
      selectAll: 'Select all notifications',
      markRead: 'Mark selected as read',
      clearAll: 'Clear all notifications',
      noNotifications: 'No notifications. You’re all caught up.',
    },
    footer: {
      brand: 'Gacharage Tea Factory',
      findUs: 'Find us',
      email: 'info@gacharagetea.co.ke',
      phone: '+254 7 90 269 182',
      navigation: 'Navigation',
      about: 'About',
      blog: 'Blog',
      privacy: 'Privacy',
      organization: 'Organization',
      leadership: 'Leadership',
      markets: 'Markets',
      terms: 'Terms and Conditions apply',
      description: 'Premium tea blends from Murang\'a County, Kenya.',
      contact: 'Contact',
      legals: 'Legals',
      shop: 'Shop',
      cart: 'Cart',
      profile: 'Profile',
    },
    homepage: {
      cartHeading: 'Cart',
      cartDescription: 'Your cart is ready for checkout. Add your favorite teas and accessories, then head to checkout when you are ready.',
      profileHeading: 'Profile',
      profileDescription: 'Manage your preferences, saved blends, and delivery details from your profile section.',
    },
    login: {
      title: 'Login',
      description: 'Sign in to access your cart, saved blends, and account settings.',
      emailPlaceholder: 'Email',
      passwordPlaceholder: 'Password',
      continue: 'Continue',
      noAccount: 'Don’t have an account yet?',
      createAccount: 'Create one.',
      errorEmpty: 'Please enter your email and password.',
    },
    register: {
      title: 'Create account',
      description: 'Register to save your favorite blends, access profile actions, and checkout faster.',
      fullNamePlaceholder: 'Full name',
      emailPlaceholder: 'Email',
      passwordPlaceholder: 'Password',
      createAccount: 'Create account',
      haveAccount: 'Already have an account?',
      signIn: 'Sign in',
      errorEmpty: 'Please provide an email and password.',
    },
    shop: {
      title: 'Shop',
      description: 'Discover our full collection of chai blends, loose leaf tea, and accessories.',
      loadingProducts: 'Loading products...',
    },
    product: {
      notFoundTitle: 'Product not found',
      notFoundCopy: 'We couldn’t find that product. Try browsing the shop instead.',
      backToShop: 'Back to Shop',
      detailsTitle: 'Product details',
      detailsCopy: 'Use this page to explore the product and add it to your cart before checkout.',
      addToCart: 'Add to Cart',
      addToWishlist: 'Add to wishlist',
      category: 'Category',
      stock: 'Stock',
      price: 'Price',
    },
    paymentQr: {
      title: 'Pay with QR code',
      description: 'Scan this QR code with your mobile payment app to complete the order.',
      noPaymentInfo: 'No payment info available',
      amountLabel: 'Amount:',
      referenceLabel: 'Reference:',
      back: 'Back',
    },
  },
  es: {
    header: {
      searchPlaceholder: 'Buscar en Chai...',
      searchPrompt: 'Busca en nuestra tienda por nombre, mezcla o artículo.',
      searchNoResults: 'No se encontraron coincidencias. Prueba con otro sabor.',
      cancel: 'Cancelar',
      clearSearch: 'Borrar búsqueda',
      openSearch: 'Abrir búsqueda',
      changeLanguage: 'Cambiar idioma',
      shop: 'Tienda',
      cart: 'Carrito',
      profile: 'Perfil',
      login: 'Iniciar sesión',
      logout: 'Cerrar sesión',
      notifications: 'Notificaciones',
      notificationsPrompt: 'Toca un elemento o usa las acciones',
      selectAll: 'Seleccionar todo',
      markRead: 'Marcar seleccionado como leído',
      clearAll: 'Borrar todo',
      noNotifications: 'No hay notificaciones. Estás al día.',
    },
    footer: {
      brand: 'Fábrica de Té Gacharage',
      findUs: 'Encuéntranos',
      email: 'info@gacharagetea.co.ke',
      phone: '+254 7 90 269 182',
      navigation: 'Navegación',
      about: 'Acerca de',
      blog: 'Blog',
      privacy: 'Privacidad',
      organization: 'Organización',
      leadership: 'Liderazgo',
      markets: 'Mercados',
      terms: 'Se aplican términos y condiciones',
      description: 'Mezclas de té premium de Murang\'a County, Kenia.',
      contact: 'Contacto',
      legals: 'Legales',
      shop: 'Tienda',
      cart: 'Carrito',
      profile: 'Perfil',
    },
    homepage: {
      cartHeading: 'Carrito',
      cartDescription: 'Tu carrito está listo para pagar. Agrega tus tés y accesorios favoritos, luego pasa al pago cuando estés listo.',
      profileHeading: 'Perfil',
      profileDescription: 'Gestiona tus preferencias, mezclas guardadas y detalles de envío desde tu perfil.',
    },
    login: {
      title: 'Iniciar sesión',
      description: 'Accede para ver tu carrito, mezclas guardadas y configuración de cuenta.',
      emailPlaceholder: 'Correo electrónico',
      passwordPlaceholder: 'Contraseña',
      continue: 'Continuar',
      noAccount: '¿No tienes una cuenta?',
      createAccount: 'Crear una.',
      errorEmpty: 'Por favor ingresa tu correo y contraseña.',
    },
    register: {
      title: 'Crear cuenta',
      description: 'Regístrate para guardar tus mezclas favoritas, acceder a acciones de perfil y pagar más rápido.',
      fullNamePlaceholder: 'Nombre completo',
      emailPlaceholder: 'Correo electrónico',
      passwordPlaceholder: 'Contraseña',
      createAccount: 'Crear cuenta',
      haveAccount: '¿Ya tienes una cuenta?',
      signIn: 'Inicia sesión',
      errorEmpty: 'Por favor proporciona correo y contraseña.',
    },
    shop: {
      title: 'Tienda',
      description: 'Descubre nuestra colección completa de mezclas chai, té suelto y accesorios.',
      loadingProducts: 'Cargando productos...',
    },
    product: {
      notFoundTitle: 'Producto no encontrado',
      notFoundCopy: 'No pudimos encontrar ese producto. Prueba navegando por la tienda.',
      backToShop: 'Volver a la tienda',
      detailsTitle: 'Detalles del producto',
      detailsCopy: 'Usa esta página para explorar el producto y agregarlo a tu carrito antes de pagar.',
      addToCart: 'Agregar al carrito',
      addToWishlist: 'Agregar a favoritos',
      category: 'Categoría',
      stock: 'Inventario',
      price: 'Precio',
    },
    paymentQr: {
      title: 'Pagar con código QR',
      description: 'Escanea este código QR con tu app de pago móvil para completar el pedido.',
      noPaymentInfo: 'No hay información de pago disponible',
      amountLabel: 'Monto:',
      referenceLabel: 'Referencia:',
      back: 'Regresar',
    },
  },
  fr: {
    header: {
      searchPlaceholder: 'Rechercher dans Chai...',
      searchPrompt: 'Recherchez dans notre boutique par nom, mélange ou article.',
      searchNoResults: 'Aucun résultat trouvé. Essayez une autre saveur.',
      cancel: 'Annuler',
      clearSearch: 'Effacer la recherche',
      openSearch: 'Ouvrir la recherche',
      changeLanguage: 'Changer de langue',
      shop: 'Boutique',
      cart: 'Panier',
      profile: 'Profil',
      login: 'Connexion',
      logout: 'Déconnexion',
      notifications: 'Notifications',
      notificationsPrompt: 'Appuyez sur un élément ou utilisez les actions',
      selectAll: 'Tout sélectionner',
      markRead: 'Marquer comme lu',
      clearAll: 'Tout effacer',
      noNotifications: 'Pas de notifications. Vous êtes à jour.',
    },
    footer: {
      brand: 'Usine de thé Gacharage',
      findUs: 'Nous trouver',
      email: 'info@gacharagetea.co.ke',
      phone: '+254 7 90 269 182',
      navigation: 'Navigation',
      about: 'À propos',
      blog: 'Blog',
      privacy: 'Confidentialité',
      organization: 'Organisation',
      leadership: 'Leadership',
      markets: 'Marchés',
      terms: 'Conditions générales applicables',
      description: 'Mélanges de thé premium du comté de Murang\'a, Kenya.',
      contact: 'Contact',
      legals: 'Mentions légales',
      shop: 'Boutique',
      cart: 'Panier',
      profile: 'Profil',
    },
    homepage: {
      cartHeading: 'Panier',
      cartDescription: 'Votre panier est prêt pour le paiement. Ajoutez vos thés et accessoires préférés, puis passez à la caisse lorsque vous êtes prêt.',
      profileHeading: 'Profil',
      profileDescription: 'Gérez vos préférences, mélanges enregistrés et informations de livraison depuis votre profil.',
    },
    login: {
      title: 'Connexion',
      description: 'Connectez-vous pour accéder à votre panier, mélanges enregistrés et paramètres de compte.',
      emailPlaceholder: 'E-mail',
      passwordPlaceholder: 'Mot de passe',
      continue: 'Continuer',
      noAccount: 'Pas encore de compte ?',
      createAccount: 'Créer un compte.',
      errorEmpty: 'Veuillez entrer votre e-mail et mot de passe.',
    },
    register: {
      title: 'Créer un compte',
      description: 'Inscrivez-vous pour enregistrer vos mélanges préférés, accéder au profil et payer plus vite.',
      fullNamePlaceholder: 'Nom complet',
      emailPlaceholder: 'E-mail',
      passwordPlaceholder: 'Mot de passe',
      createAccount: 'Créer un compte',
      haveAccount: 'Vous avez déjà un compte ?',
      signIn: 'Se connecter',
      errorEmpty: 'Veuillez fournir un e-mail et un mot de passe.',
    },
    shop: {
      title: 'Boutique',
      description: 'Découvrez notre collection complète de mélanges chai, thés en vrac et accessoires.',
      loadingProducts: 'Chargement des produits...',
    },
    product: {
      notFoundTitle: 'Produit introuvable',
      notFoundCopy: 'Nous n’avons pas trouvé ce produit. Essayez de parcourir la boutique.',
      backToShop: 'Retour à la boutique',
      detailsTitle: 'Détails du produit',
      detailsCopy: 'Utilisez cette page pour explorer le produit et l’ajouter à votre panier avant de payer.',
      addToCart: 'Ajouter au panier',
      addToWishlist: 'Ajouter à la liste',
      category: 'Catégorie',
      stock: 'Stock',
      price: 'Prix',
    },
    paymentQr: {
      title: 'Payer avec QR code',
      description: 'Scannez ce QR code avec votre application de paiement mobile pour terminer la commande.',
      noPaymentInfo: 'Aucune information de paiement disponible',
      amountLabel: 'Montant:',
      referenceLabel: 'Référence:',
      back: 'Retour',
    },
  },
  de: {
    header: {
      searchPlaceholder: 'In Chai suchen...',
      searchPrompt: 'Durchsuchen Sie unseren Shop nach Name, Mischung oder Artikel.',
      searchNoResults: 'Keine Treffer gefunden. Versuchen Sie einen anderen Geschmack.',
      cancel: 'Abbrechen',
      clearSearch: 'Suche löschen',
      openSearch: 'Suche öffnen',
      changeLanguage: 'Sprache ändern',
      shop: 'Shop',
      cart: 'Warenkorb',
      profile: 'Profil',
      login: 'Anmelden',
      logout: 'Abmelden',
      notifications: 'Benachrichtigungen',
      notificationsPrompt: 'Tippen Sie auf einen Eintrag oder nutzen Sie die Aktionen',
      selectAll: 'Alle auswählen',
      markRead: 'Als gelesen markieren',
      clearAll: 'Alle löschen',
      noNotifications: 'Keine Benachrichtigungen. Sie sind auf dem neuesten Stand.',
    },
    footer: {
      brand: 'Gacharage Tee-Fabrik',
      findUs: 'Finde uns',
      email: 'info@gacharagetea.co.ke',
      phone: '+254 7 90 269 182',
      navigation: 'Navigation',
      about: 'Über uns',
      blog: 'Blog',
      privacy: 'Datenschutz',
      organization: 'Organisation',
      leadership: 'Führung',
      markets: 'Märkte',
      terms: 'Es gelten die Geschäftsbedingungen',
      description: 'Premium-Teemischungen aus dem Landkreis Murang\'a, Kenia.',
      contact: 'Kontakt',
      legals: 'Rechtsinformationen',
      shop: 'Shop',
      cart: 'Warenkorb',
      profile: 'Profil',
    },
    homepage: {
      cartHeading: 'Warenkorb',
      cartDescription: 'Ihr Warenkorb ist bereit zur Kasse. Fügen Sie Ihre Lieblingstees und Accessoires hinzu und gehen Sie zur Kasse, wenn Sie bereit sind.',
      profileHeading: 'Profil',
      profileDescription: 'Verwalten Sie Ihre Einstellungen, gespeicherten Mischungen und Lieferdetails in Ihrem Profil.',
    },
    login: {
      title: 'Anmelden',
      description: 'Melden Sie sich an, um auf Ihren Warenkorb, gespeicherte Mischungen und Kontoeinstellungen zuzugreifen.',
      emailPlaceholder: 'E-Mail',
      passwordPlaceholder: 'Passwort',
      continue: 'Weiter',
      noAccount: 'Noch kein Konto?',
      createAccount: 'Erstellen Sie eines.',
      errorEmpty: 'Bitte geben Sie Ihre E-Mail und Ihr Passwort ein.',
    },
    register: {
      title: 'Konto erstellen',
      description: 'Registrieren Sie sich, um Ihre Lieblingstees zu speichern, auf Profilaktionen zuzugreifen und schneller zu bezahlen.',
      fullNamePlaceholder: 'Vollständiger Name',
      emailPlaceholder: 'E-Mail',
      passwordPlaceholder: 'Passwort',
      createAccount: 'Konto erstellen',
      haveAccount: 'Haben Sie bereits ein Konto?',
      signIn: 'Anmelden',
      errorEmpty: 'Bitte geben Sie eine E-Mail und ein Passwort an.',
    },
    shop: {
      title: 'Shop',
      description: 'Entdecken Sie unsere komplette Sammlung an Chai-Mischungen, losen Tees und Zubehör.',
      loadingProducts: 'Produkte werden geladen...',
    },
    product: {
      notFoundTitle: 'Produkt nicht gefunden',
      notFoundCopy: 'Wir konnten dieses Produkt nicht finden. Versuchen Sie, den Shop zu durchsuchen.',
      backToShop: 'Zurück zum Shop',
      detailsTitle: 'Produktdetails',
      detailsCopy: 'Verwenden Sie diese Seite, um das Produkt zu erkunden und vor dem Kauf in den Warenkorb zu legen.',
      addToCart: 'In den Warenkorb',
      addToWishlist: 'Zur Wunschliste hinzufügen',
      category: 'Kategorie',
      stock: 'Lagerbestand',
      price: 'Preis',
    },
    paymentQr: {
      title: 'Mit QR-Code bezahlen',
      description: 'Scannen Sie diesen QR-Code mit Ihrer mobilen Zahlungs-App, um die Bestellung abzuschließen.',
      noPaymentInfo: 'Keine Zahlungsinformationen verfügbar',
      amountLabel: 'Betrag:',
      referenceLabel: 'Referenz:',
      back: 'Zurück',
    },
  },
  sw: {
    header: {
      searchPlaceholder: 'Tafuta Chai...',
      searchPrompt: 'Tafuta kwenye duka letu kwa jina, mchanganyiko, au bidhaa.',
      searchNoResults: 'Hakuna matokeo. Jaribu ladha nyingine.',
      cancel: 'Ghairi',
      clearSearch: 'Futa utafutaji',
      openSearch: 'Fungua utafutaji',
      changeLanguage: 'Badilisha lugha',
      shop: 'Duka',
      cart: 'Kikapu',
      profile: 'Profaili',
      login: 'Ingia',
      logout: 'Toka',
      notifications: 'Arifa',
      notificationsPrompt: 'Gusa kipengee au tumia vitendo',
      selectAll: 'Chagua zote',
      markRead: 'Taja zilizo chaguliwa kama kusomwa',
      clearAll: 'Futa zote',
      noNotifications: 'Hakuna arifa. Uko sawa.',
    },
    footer: {
      brand: 'Kiwanda cha Chai cha Gacharage',
      findUs: 'Tupate',
      email: 'info@gacharagetea.co.ke',
      phone: '+254 7 90 269 182',
      navigation: 'Uelekezaji',
      about: 'Kuhusu',
      blog: 'Blogu',
      privacy: 'Faragha',
      organization: 'Shirika',
      leadership: 'Uongozi',
      markets: 'Soko',
      terms: 'Masharti na masharti yanatumika',
      description: 'Mchanganyiko ya chai ya premium kutoka Kaunti ya Murang\'a, Kenya.',
      contact: 'Mawasiliano',
      legals: 'Sheria',
      shop: 'Duka',
      cart: 'Kikapu',
      profile: 'Profaili',
    },
    homepage: {
      cartHeading: 'Kikapu',
      cartDescription: 'Kikapu chako kiko tayari kwa malipo. Ongeza chai na vifaa unavyopenda, kisha nenda kwa malipo unapokuwa tayari.',
      profileHeading: 'Profaili',
      profileDescription: 'Simamia upendeleo wako, mchanganyiko uliohifadhiwa, na maelezo ya usafirishaji kutoka kwenye profaili yako.',
    },
    login: {
      title: 'Ingia',
      description: 'Ingia ili kupata kikapu chako, mchanganyiko ulihifadhiwa, na mipangilio ya akaunti.',
      emailPlaceholder: 'Barua pepe',
      passwordPlaceholder: 'Nenosiri',
      continue: 'Endelea',
      noAccount: 'Huna akaunti bado?',
      createAccount: 'Unda moja.',
      errorEmpty: 'Tafadhali ingiza barua pepe na nenosiri.',
    },
    register: {
      title: 'Unda akaunti',
      description: 'Jisajili ili kuhifadhi mchanganyiko unaopenda, kupata vitendo vya profaili, na kulipa haraka.',
      fullNamePlaceholder: 'Jina kamili',
      emailPlaceholder: 'Barua pepe',
      passwordPlaceholder: 'Nenosiri',
      createAccount: 'Unda akaunti',
      haveAccount: 'Tayari una akaunti?',
      signIn: 'Ingia',
      errorEmpty: 'Tafadhali toa barua pepe na nenosiri.',
    },
    shop: {
      title: 'Duka',
      description: 'Gundua mkusanyiko wetu kamili wa mchanganyiko wa chai, chai kibao, na vifaa.',
      loadingProducts: 'Inapakia bidhaa...',
    },
    product: {
      notFoundTitle: 'Bidhaa haikupatikana',
      notFoundCopy: 'Hatuwezi kupata bidhaa hiyo. Jaribu kuvinjari duka badala yake.',
      backToShop: 'Rudi dukani',
      detailsTitle: 'Maelezo ya bidhaa',
      detailsCopy: 'Tumia ukurasa huu kuchunguza bidhaa na kuiweka kwingi kabla ya malipo.',
      addToCart: 'Ongeza kwenye kikapu',
      addToWishlist: 'Ongeza kwenye orodha ya matamanio',
      category: 'Jamii',
      stock: 'Hisa',
      price: 'Bei',
    },
    paymentQr: {
      title: 'Lipia kwa QR',
      description: 'Skana QR hii kwa programu yako ya malipo ya simu ili kumaliza oda.',
      noPaymentInfo: 'Hakuna taarifa za malipo',
      amountLabel: 'Kiasi:',
      referenceLabel: 'Rejea:',
      back: 'Rudi',
    },
  },
  zh: {
    header: {
      searchPlaceholder: '搜索 Chai...',
      searchPrompt: '按名称、混合或商品搜索我们的商店。',
      searchNoResults: '未找到匹配项。请尝试其他口味。',
      cancel: '取消',
      clearSearch: '清除搜索',
      openSearch: '打开搜索',
      changeLanguage: '更改语言',
      shop: '商店',
      cart: '购物车',
      profile: '个人资料',
      login: '登录',
      logout: '登出',
      notifications: '通知',
      notificationsPrompt: '点击项目或使用操作',
      selectAll: '全选',
      markRead: '标记为已读',
      clearAll: '清除全部',
      noNotifications: '没有通知。全部完成。',
    },
    footer: {
      brand: 'Gacharage 茶厂',
      findUs: '联系我们',
      email: 'info@gacharagetea.co.ke',
      phone: '+254 7 90 269 182',
      navigation: '导航',
      about: '关于',
      blog: '博客',
      privacy: '隐私',
      organization: '组织',
      leadership: '领导',
      markets: '市场',
      terms: '适用条款和条件',
      description: '来自肯尼亚穆朗加县的优质茶叶混合。',
      contact: '联系我们',
      legals: '法律声明',
      shop: '商店',
      cart: '购物车',
      profile: '个人资料',
    },
    homepage: {
      cartHeading: '购物车',
      cartDescription: '您的购物车已准备好结账。添加您喜欢的茶和配件，然后准备好时结账。',
      profileHeading: '个人资料',
      profileDescription: '从个人资料部分管理您的偏好、已保存的混合和送货详情。',
    },
    login: {
      title: '登录',
      description: '登录以访问您的购物车、已保存的混合和帐户设置。',
      emailPlaceholder: '电子邮箱',
      passwordPlaceholder: '密码',
      continue: '继续',
      noAccount: '还没有账户？',
      createAccount: '创建一个。',
      errorEmpty: '请输入您的电子邮件和密码。',
    },
    register: {
      title: '创建账户',
      description: '注册以保存您喜爱的混合，访问个人资料操作并更快结账。',
      fullNamePlaceholder: '全名',
      emailPlaceholder: '电子邮箱',
      passwordPlaceholder: '密码',
      createAccount: '创建账户',
      haveAccount: '已经有账户？',
      signIn: '登录',
      errorEmpty: '请输入电子邮箱和密码。',
    },
    shop: {
      title: '商店',
      description: '发现我们的整套 chai 混合、散茶和配件系列。',
      loadingProducts: '正在加载产品...',
    },
    product: {
      notFoundTitle: '未找到产品',
      notFoundCopy: '我们无法找到该产品。请尝试浏览商店。',
      backToShop: '返回商店',
      detailsTitle: '产品详情',
      detailsCopy: '使用此页面浏览产品并在结账前将其添加到购物车。',
      addToCart: '添加到购物车',
      addToWishlist: '添加到愿望清单',
      category: '类别',
      stock: '库存',
      price: '价格',
    },
    paymentQr: {
      title: '使用二维码支付',
      description: '使用您的移动支付应用扫描此二维码以完成订单。',
      noPaymentInfo: '没有可用的支付信息',
      amountLabel: '金额:',
      referenceLabel: '参考:',
      back: '返回',
    },
  },
}

const getTranslation = (locale, key) => {
  const parts = key.split('.')
  let current = translations[locale]
  for (const part of parts) {
    if (!current) return undefined
    current = current[part]
  }
  return current
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('preferredLanguage') || 'en'
    }
    return 'en'
  })

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('preferredLanguage', language)
    }
  }, [language])

  const languages = [
    { code: 'en', label: 'English', flag: '🇬🇧' },
    { code: 'es', label: 'Español', flag: '🇪🇸' },
    { code: 'fr', label: 'Français', flag: '🇫🇷' },
    { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
    { code: 'sw', label: 'Kiswahili', flag: '🇰🇪' },
    { code: 'zh', label: '中文', flag: '🇨🇳' },
  ]

  const t = useMemo(
    () => (key) => {
      return getTranslation(language, key) || getTranslation('en', key) || key
    },
    [language]
  )

  const switchLanguage = (code) => {
    setLanguage(code)
  }

  return (
    <LanguageContext.Provider value={{ language, languages, switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
